#!/usr/bin/env bash
# =============================================================================
# scripts/secrets/pull-secrets.sh — Social Engine
# Pull secrets from GCP Secret Manager and write to local .env file
# Naming convention: social-engine-{env}-{var-name}
#
# Usage:
#   ./scripts/secrets/pull-secrets.sh [dev|prod]
#
# Prerequisites:
#   - gcloud CLI authenticated: gcloud auth login
#   - Project set: gcloud config set project ffe-cicd
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
GCP_PROJECT="ffe-cicd"
ENV="${1:-dev}"

if [[ "$ENV" != "dev" && "$ENV" != "prod" ]]; then
  echo "Usage: $0 [dev|prod]"
  exit 1
fi

if [[ "$ENV" == "dev" ]]; then
  OUT_FILE="$REPO_ROOT/apps/dashboard/.env.local"
else
  OUT_FILE="$REPO_ROOT/apps/dashboard/.env.production"
fi

echo "Pulling social-engine $ENV secrets from GCP SM project: $GCP_PROJECT"
echo "Output file: $OUT_FILE"
echo ""

# Map: GCP SM secret name → env var name
declare -A SECRET_MAP=(
  ["social-engine-${ENV}-clerk-publishable-key"]="NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY"
  ["social-engine-${ENV}-clerk-secret-key"]="CLERK_SECRET_KEY"
  ["social-engine-${ENV}-clerk-webhook-secret"]="CLERK_WEBHOOK_SECRET"
  ["social-engine-${ENV}-convex-url"]="NEXT_PUBLIC_CONVEX_URL"
  ["social-engine-${ENV}-convex-deployment"]="CONVEX_DEPLOYMENT"
  ["social-engine-${ENV}-zernio-api-key"]="ZERNIO_API_KEY"
  ["social-engine-${ENV}-google-api-key"]="GOOGLE_API_KEY"
  ["social-engine-${ENV}-google-maps-api-key"]="NEXT_PUBLIC_GOOGLE_MAPS_API_KEY"
  ["social-engine-${ENV}-posthog-key"]="NEXT_PUBLIC_POSTHOG_KEY"
  ["social-engine-${ENV}-sentry-dsn"]="SENTRY_DSN"
  ["social-engine-${ENV}-stripe-secret-key"]="STRIPE_SECRET_KEY"
  ["social-engine-${ENV}-stripe-webhook-secret"]="STRIPE_WEBHOOK_SECRET"
  ["social-engine-${ENV}-stripe-publishable-key"]="NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY"
)

# Start fresh output
{
  echo "# Auto-generated by scripts/secrets/pull-secrets.sh — DO NOT COMMIT"
  echo "# Environment: $ENV | Generated: $(date -u '+%Y-%m-%dT%H:%M:%SZ')"
  echo ""
  echo "NEXT_PUBLIC_CLERK_SIGN_IN_URL=/sign-in"
  echo "NEXT_PUBLIC_CLERK_SIGN_UP_URL=/sign-up"
  echo "NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL=/dashboard"
  echo "NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL=/dashboard"
  echo "NEXT_PUBLIC_POSTHOG_HOST=https://app.posthog.com"
  echo "SENTRY_ORG=fireflyevents"
  echo "SENTRY_PROJECT=social-engine"
  echo "NODE_ENV=${ENV}"
  if [[ "$ENV" == "dev" ]]; then
    echo "NEXT_PUBLIC_APP_URL=http://localhost:3000"
  else
    echo "NEXT_PUBLIC_APP_URL=https://social-engine-five.vercel.app"
  fi
  echo ""
} > "$OUT_FILE"

for secret_name in "${!SECRET_MAP[@]}"; do
  var_name="${SECRET_MAP[$secret_name]}"
  value=$(gcloud secrets versions access latest \
    --secret="$secret_name" \
    --project="$GCP_PROJECT" 2>/dev/null || echo "")

  if [[ -z "$value" ]]; then
    echo "  MISSING: $secret_name (skipped)"
    echo "# MISSING: ${var_name}=" >> "$OUT_FILE"
  else
    echo "  OK: $var_name"
    echo "${var_name}=${value}" >> "$OUT_FILE"
  fi
done

echo ""
echo "Written to $OUT_FILE"
echo "WARNING: This file is gitignored. Never commit it."
